library(httr)
library(httpuv)
myapp <- oauth_app("github",key="add_your_registered_key",secret = "add_your_secret")
github_token <- oauth2.0_token(oauth_endpoints("github"), myapp)
gtoken <- config(token = github_token)
req <- GET("https://api.github.com/rate_limit", gtoken)
stop_for_status(req)
content(req)